# Generated by Django 5.2.7 on 2025-10-17 17:59

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0004_pinnedpredictor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pinnedpredictor',
            options={'verbose_name': 'Pinned Predictor', 'verbose_name_plural': 'Pinned Predictors'},
        ),
        migrations.AlterModelOptions(
            name='predictor',
            options={'ordering': ['name'], 'verbose_name': 'Predictor', 'verbose_name_plural': 'Predictors'},
        ),
        migrations.AlterModelOptions(
            name='predictorpermission',
            options={'verbose_name': 'Predictor Permission', 'verbose_name_plural': 'Predictor Permissions'},
        ),
        migrations.AddField(
            model_name='predictor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='predictor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='predictorpermission',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddIndex(
            model_name='pinnedpredictor',
            index=models.Index(fields=['user'], name='predictors__user_id_ca3cbc_idx'),
        ),
        migrations.AddIndex(
            model_name='pinnedpredictor',
            index=models.Index(fields=['predictor'], name='predictors__predict_d17efc_idx'),
        ),
        migrations.AddIndex(
            model_name='predictorpermission',
            index=models.Index(fields=['user'], name='predictors__user_id_5a515f_idx'),
        ),
        migrations.AddIndex(
            model_name='predictorpermission',
            index=models.Index(fields=['predictor'], name='predictors__predict_b80a20_idx'),
        ),
    ]
