# Generated by Django 5.2.7 on 2025-10-23 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0007_alter_pinnedpredictor_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictor',
            name='base_predictor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_predictors', to='predictors.predictor'),
        ),
        migrations.AddField(
            model_name='predictor',
            name='metrics',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='predictor',
            name='model_artifact',
            field=models.FileField(blank=True, null=True, upload_to='models/'),
        ),
    ]
