# Generated by Django 5.2.7 on 2025-10-24 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0007_alter_pinnedpredictor_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictor',
            name='allow_admin_access',
            field=models.BooleanField(default=False),
        ),
    ]
