# Generated by Django 5.2.7 on 2025-10-25 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0007_alter_pinnedpredictor_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictor',
            name='allow_admin_access',
        ),
        migrations.AlterField(
            model_name='predictor',
            name='time_unit',
            field=models.CharField(choices=[('day', 'Day'), ('hour', 'Hour'), ('month', 'Month'), ('year', 'Year')], default='day', max_length=10),
        ),
    ]
