# Generated by Django 5.2.7 on 2025-10-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0007_alter_pinnedpredictor_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictorpermission',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('viewer', 'Viewer')], default='viewer', max_length=10),
        ),
    ]
