# Generated by Django 5.2.7 on 2025-10-23 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0007_alter_pinnedpredictor_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictor',
            name='allow_admin_access',
        ),
    ]
