# Generated by Django 5.2.7 on 2025-10-25 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0008_predictorpermission_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictor',
            name='allow_admin_access',
        ),
    ]
