# Generated by Django 5.2.7 on 2025-10-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0009_remove_predictor_allow_admin_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictor',
            name='allow_admin_access',
            field=models.BooleanField(default=False),
        ),
    ]
