# Generated by Django 5.2.7 on 2025-10-25 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictors', '0010_predictor_allow_admin_access'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictor',
            name='allow_admin_access',
        ),
    ]
