# Project Key 
sonar.projectKey=isd

# Authentication
sonar.login=sqp_ac6fbc27a212a2bfce5d3e8fb3d932182fef74b0

# --- PATHS ---
sonar.sources=isd
sonar.python.coverage.reportPaths=backend/coverage.xml

# --- EXCLUSIONS ---
sonar.exclusions=**/migrations/**, **/venv/**, **/__pycache__**, **/tests.py, **/test_*.py